# Generated by Django 4.2.5 on 2024-04-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='درصد تخفیف %'),
        ),
    ]
