# Generated by Django 4.2.5 on 2024-04-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Discount',
            field=models.IntegerField(default=0, null=True, verbose_name='درصد تخفیف %'),
        ),
    ]
