# Generated by Django 4.2.5 on 2024-05-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='موجودی کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Discount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='درصد تخفیف %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
    ]
