# Generated by Django 4.2.5 on 2024-08-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_product_is_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductTag',
        ),
    ]
