# Generated by Django 4.2.5 on 2024-09-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_delete_producttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='whatsup_link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک واتساپ محصول'),
        ),
    ]
