# Generated by Django 4.2.5 on 2024-09-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_product_instagram_link_product_whatsup_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
    ]
