# Generated by Django 4.2.5 on 2024-07-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0004_alter_orderdetail_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='مبلغ نهایی'),
        ),
    ]
