# Generated by Django 4.2.5 on 2024-07-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0005_order_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='مبلغ نهایی'),
        ),
    ]
