# Generated by Django 4.2.5 on 2024-08-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0009_alter_order_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
