# Generated by Django 4.2.5 on 2024-08-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0010_alter_order_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='آیا سفارش ثبت شده است؟'),
        ),
    ]
