# Generated by Django 4.2.5 on 2024-08-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0013_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
