# Generated by Django 4.2.5 on 2024-08-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0015_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='آیا پیام خوانده شده؟'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
    ]
