# Generated by Django 4.2.5 on 2024-08-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0016_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلان ها'},
        ),
    ]
