# Generated by Django 4.2.5 on 2024-08-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0017_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت سفارش'),
        ),
    ]
