# Generated by Django 4.2.5 on 2024-08-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0018_order_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='ساخته شده در تاریخ'),
        ),
    ]
