# Generated by Django 4.2.5 on 2024-05-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_module', '0002_alter_productcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default='images/categories/category_default.png', upload_to='images/categories', verbose_name='تصویر دسته بندی'),
        ),
    ]
