# Generated by Django 4.2.5 on 2024-02-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_module', '0003_remove_productbrand_parent_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='parent_brand',
            new_name='parent_category',
        ),
    ]
