# Generated by Django 4.2.5 on 2024-02-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_module', '0004_rename_parent_brand_productcategory_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='url_title',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='عنوان در URL'),
        ),
    ]
