# Generated by Django 4.2.5 on 2024-03-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_module', '0005_alter_productcategory_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories', verbose_name='تصویر دسته بندی'),
        ),
    ]
