# Generated by Django 4.2.5 on 2024-03-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_module', '0006_productcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, default='images/categories/category_default.png', null=True, upload_to='images/categories', verbose_name='تصویر دسته بندی'),
        ),
    ]
