# Generated by Django 4.2.5 on 2024-03-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_module', '0008_alter_productcategory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='url_title',
            new_name='slug',
        ),
    ]
