# Generated by Django 4.2.5 on 2023-10-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='address2',
            field=models.CharField(blank=True, max_length=300, verbose_name='آدرس2'),
        ),
    ]
