# Generated by Django 4.2.5 on 2024-04-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
