# Generated by Django 4.2.5 on 2024-05-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_delete_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(upload_to='media/images/site-setting/', verbose_name='لوگو سایت'),
        ),
    ]
