# Generated by Django 4.2.5 on 2024-07-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_alter_sitesetting_site_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=100, verbose_name='متن اول')),
                ('text2', models.CharField(max_length=100, verbose_name='متن دوم')),
                ('text3', models.CharField(max_length=100, verbose_name='متن سوم')),
                ('text4', models.CharField(max_length=100, verbose_name='متن چهارم')),
                ('text5', models.CharField(max_length=100, verbose_name='متن پنجم')),
                ('text6', models.CharField(max_length=100, verbose_name='متن ششم')),
            ],
            options={
                'verbose_name': 'تبلیغ هدر سایت',
                'verbose_name_plural': 'تبلیغات هدر سایت',
            },
        ),
    ]
