# Generated by Django 4.2.5 on 2024-07-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_mission', models.TextField(verbose_name='ماموریت ما:')),
                ('our_vision', models.TextField(verbose_name='دیدگاه ما:')),
                ('our_philosophy', models.TextField(verbose_name='فلسفه ما:')),
                ('we_are_trusted', models.TextField(verbose_name='به ما اعتماد کنید زیرا:')),
                ('we_are_professional', models.TextField(verbose_name='ما حرفه ای هستیم زیرا:')),
                ('our_stories', models.TextField(verbose_name='داستان ما:')),
            ],
        ),
    ]
