# Generated by Django 4.2.5 on 2024-07-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='موضوع')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='images/about_us', verbose_name='تصویر درباره ما')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره های ما',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'سرویس ما', 'verbose_name_plural': 'سرویس های ما'},
        ),
    ]
