# Generated by Django 4.2.5 on 2024-08-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0007_aboutus_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'تبلیغ بالای سایت', 'verbose_name_plural': 'تبلیغات بالای سایت'},
        ),
    ]
