# Generated by Django 4.2.5 on 2024-09-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0009_sitesetting_eitaa_link_sitesetting_roobika_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='our_philosophy',
        ),
        migrations.RemoveField(
            model_name='service',
            name='our_vision',
        ),
        migrations.RemoveField(
            model_name='service',
            name='we_are_trusted',
        ),
        migrations.AlterField(
            model_name='service',
            name='our_mission',
            field=models.TextField(verbose_name='نمایندگان ما:'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='eitaa_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک ایتا همراه با (//:https)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک اینستاگرام همراه با (//:https)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='roobika_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک روبیکا همراه با (//:https)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_url',
            field=models.CharField(max_length=200, verbose_name='نام دامنه سایت بدون (//:https)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک تلگرام همراه با (//:https)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک واتساپ همراه با (//:https)'),
        ),
    ]
