# Generated by Django 4.2.5 on 2024-02-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slides',
            options={'verbose_name': 'اسلاید', 'verbose_name_plural': 'اسلاید ها'},
        ),
    ]
