# Generated by Django 4.2.5 on 2024-04-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.CharField(max_length=400, verbose_name='توضیحات اسلایدر'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='images/slides', verbose_name='تصویر اسلایدر'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.URLField(max_length=300, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='link_title',
            field=models.CharField(max_length=50, verbose_name='عنوان لینک'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
    ]
