# Generated by Django 4.2.5 on 2024-02-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_alter_slides_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='slides',
            new_name='slide',
        ),
    ]
