# Generated by Django 4.2.5 on 2024-02-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_rename_slides_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='link',
            field=models.URLField(default='http://localhost:8000/', max_length=300),
            preserve_default=False,
        ),
    ]
