# Generated by Django 4.2.5 on 2024-05-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_alter_instagram_image_alter_slide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='image',
            field=models.ImageField(default='images/instagrams/insta-logo.png', upload_to='images/instagrams'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='images/slides', verbose_name='تصویر اسلایدر'),
        ),
    ]
