# Generated by Django 4.2.5 on 2024-03-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0005_slide_link_title_alter_slide_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=300)),
                ('image', models.ImageField(default='images/instagrams/insta-logo.png', upload_to='images/instagrams')),
            ],
            options={
                'verbose_name': 'پست اینستاگرام',
                'verbose_name_plural': 'پست های اینستاگرام',
            },
        ),
    ]
