# Generated by Django 4.2.5 on 2024-03-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('phone_active_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='phone active code')),
                ('activation_code_expiration', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=20, verbose_name='full name')),
                ('is_active', models.BooleanField(default=False, verbose_name='is user active?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is user staff?')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/profile_images', verbose_name='profile avatar')),
            ],
            options={
                'verbose_name': 'Uesr',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
