# Generated by Django 4.2.5 on 2024-07-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_alter_factors_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_code_expiration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_active_code',
        ),
    ]
