# Generated by Django 4.2.5 on 2024-07-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0007_remove_user_activation_code_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='full name'),
        ),
    ]
