# Generated by Django 4.2.5 on 2024-08-18 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0008_alter_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_posty',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی بدون خط فاصله:'),
        ),
        migrations.AddField(
            model_name='user',
            name='melli_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی:'),
        ),
        migrations.AlterField(
            model_name='factors',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ:'),
        ),
        migrations.AlterField(
            model_name='factors',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/factors', verbose_name='فایل فاکتور:'),
        ),
        migrations.AlterField(
            model_name='factors',
            name='title',
            field=models.CharField(max_length=100, verbose_name='موضوع:'),
        ),
        migrations.AlterField(
            model_name='factors',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس شما:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نام و نام خانوادگی:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='آیا کاربر فعال است؟'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='آیا کاربر کارمند است؟'),
        ),
    ]
