# Generated by Django 4.2.5 on 2024-08-19 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0010_alter_factors_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factors',
            options={'verbose_name': 'فاکتور', 'verbose_name_plural': 'فاکتور ها'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='factors',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ:'),
        ),
        migrations.AlterField(
            model_name='factors',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='تلفن:'),
        ),
    ]
