# Generated by Django 4.2.5 on 2024-08-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0012_factors_code_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(null=True, verbose_name='آدرس شما:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_posty',
            field=models.CharField(max_length=10, null=True, verbose_name='کد پستی بدون خط فاصله:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=20, null=True, verbose_name='نام و نام خانوادگی:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='melli_code',
            field=models.CharField(max_length=10, null=True, verbose_name='کد ملی:'),
        ),
    ]
