# Generated by Django 4.2.5 on 2024-08-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0014_alter_user_code_posty_alter_user_melli_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=40, null=True, verbose_name='نام و نام خانوادگی:'),
        ),
    ]
