# Generated by Django 4.2.5 on 2024-09-05 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0018_alter_user_melli_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factors',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر:'),
        ),
    ]
