# Generated by Django 4.2.5 on 2024-09-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0019_alter_factors_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factors',
            name='code_factor',
            field=models.CharField(max_length=9, null=True, unique=True, verbose_name='کد فاکتور:'),
        ),
    ]
